### ISSUE TITLE
Simple automation for setting up PARETO in a user-specified working directory

### ISSUE THREAD

**Issue by lbianchi-lbl** [project-pareto/project-pareto#54]
## Overview

- The user workflow proposed by @MAZamarripa and @drouvenm is founded on the idea that the necessary material (example data, documentation, runnable code) should be copied over and used in a working directory chosen by the user
- @ksbeattie proposed to have an automated solution to do this, with a roughly similar functionality as (a simpler variant of) `idaes get-examples`
- This solution was well received as it has several advantages:
  - For users: streamline the user workflow with a unified, easily-documentable interface
  - For developers: make it possible (if needed) to change the implementation details (where the various material is stored, having separate directories or repositories, etc) as long as the command's interface stays the same

## Tasks

- [ ] Create entrypoint for a runnable console script, e.g. `pareto init`
- [ ] As a first pass, the functionality could consist of:
  - [ ] Copy docs and data files from model directory
  - [ ] Create runnable Python file from template

**Comment by lbianchi-lbl** [comment]
Looking back at this, it's not clear who would benefit from this functionality:

- PARETO developers (contributors) already have easy access to the entire codebase by cloning this repository to a directory of their choice
- Users who are not expected to need to access the PARETO Python API by manually editing Python scripts would not benefit from this

Given this, it seems that the target audience for this functionality would consist of Python developers who are not PARETO contributors. Since at the moment this is not anticipated to be a primary use case, we can close the issue and revisit it in the future if or when a similar set of features will be needed.
