### ISSUE TITLE
Fixing test for opening repo to the public

### ISSUE THREAD

**Issue by ksbeattie** [project-pareto/project-pareto#72]
- [x] Merge ~~PR #71~~ PR  #73
  - [x] Needs update from @lbianchi-lbl to make equivalent change to test_solvers.py
- [x] Create a run script for each case - PR #75 
  - [x] Strategic
  - [x] Operational
- [x] Push tests PR #74
